// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkyqpfzqytoaapoetolk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZreXFwZnpxeXRvYWFwb2V0b2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0ODIzNTYsImV4cCI6MjA1MjA1ODM1Nn0.TGyVAG1P-Ajoc5SGBJ6n6vvuiPejfg2VP-5qVhBshNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);